---
# ====== Application: FIMAKI-INVERSIONISTA ===================
id: 100
identification: 
  name: FIMAKI-INVERSIONISTA
  alias: FIMAKI-INV
  version: Release 1.02.000

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Native Printing

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: false
  compatibility-mode: 24.2
  accessible-read-only-items: true
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: IAM # 23380568740831911

authorization: 
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended

database-session: 
  parsing-schema: FIMAKI_APP
  initialization-pl/sql-code: execute immediate 'alter session set nls_numeric_characters = ''.,''';

globalization: 
  primary-language: Spanish (United States) (es-us)
  document-direction: Language Default
  language-derived-from: Application Primary Language
  automatic-time-zone: true
  automatic-csv-encoding: true

application-format-masks: 
  date: DD-MM-YYYY
  date-time: 'DD-MM-YYYY HH:MIPM'
  timestamp: 'DD-MM-YYYY HH:MIPM'
  timestamp-time-zone: 'DD-MM-YYYY HH24:MI TZR'

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Image
  image-url: '#APP_FILES#app-100-logo.png'

progressive-web-app: 
  enable: true
  installable: false
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:101:&APP_SESSION.::&DEBUG.:::'
    page: 101 # Landing

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - js-navCollapsed--default
  - t-TreeNav--styleA
  list-position: Side
  list: Navigation Menu # 15695018358102622

navigation-bar: 
  implementation: List
  list: Navigation Bar # 15696196735102658
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

css: 
  file-urls: 
  - '#APP_FILES#CSS/Styles#MIN#.css'

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: false
  auto-dismiss-success-messages: true

subscription: 
  version-number: 45262839559496

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: FIMAKI_INV

- # ====== Substitution: ORG_NAME ==============================
  id: 2
  identification: 
    name: ORG_NAME

  value: 
    static-value: FIMAKI

- # ====== Substitution: BASE_URL ==============================
  id: 3
  identification: 
    name: BASE_URL

  value: 
    static-value: ords/r/fimaki_ws/fimaki-inv/home

- # ====== Substitution: CURRENCY_FORMAT =======================
  id: 4
  identification: 
    name: CURRENCY_FORMAT

  value: 
    static-value: FM999G999D00

- # ====== Substitution: CURRENCY_SYMBOL =======================
  id: 5
  identification: 
    name: CURRENCY_SYMBOL

  value: 
    static-value: S/

- # ====== Substitution: DATE ==================================
  id: 6
  identification: 
    name: DATE

  value: 
    static-value: DD-MM-YYYY

- # ====== Substitution: DATE_12H ==============================
  id: 7
  identification: 
    name: DATE_12H

  value: 
    static-value: 'DD-MM-YYYY HH:MIPM'

- # ====== Substitution: DATE_24H_TZ ===========================
  id: 8
  identification: 
    name: DATE_24H_TZ

  value: 
    static-value: 'DD-MM-YYYY HH24:MI TZR'

- # ====== Substitution: YEAR ==================================
  id: 9
  identification: 
    name: YEAR

  value: 
    static-value: YYYY

- # ====== Substitution: NUMBER_FORMAT =========================
  id: 10
  identification: 
    name: NUMBER_FORMAT

  value: 
    static-value: FM999G999G990D00

component-settings: 
- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 15689768895102600
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 41717224379694

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 15689984458102603
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 41717224379697

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 15690298179102604
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  subscription: 
    version-number: 41717224379697

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 15690627660102605
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  subscription: 
    version-number: 41717224379698

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 15690862887102605
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 41717224379712

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 15691161256102606
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 41717224379713

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 15691519058102607
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  subscription: 
    version-number: 41717224379713

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 15691750295102608
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  subscription: 
    version-number: 41717224379713

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 15692051020102608
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  subscription: 
    version-number: 41717224379713

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 15692425068102609
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  subscription: 
    version-number: 41717224379713

- # ====== Component Setting: NATIVE_IR ========================
  id: 15692664575102610
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 41717224379713

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 15692939604102610
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 41717224379719

- # ====== Component Setting: NATIVE_BOSS ======================
  id: 15693283997102611
  identification: 
    name: NATIVE_BOSS
    type: REST Data Source

  subscription: 
    version-number: 41717224379719

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 15693529553102612
  identification: 
    name: NATIVE_YES_NO
    type: Item

  subscription: 
    version-number: 41717224379719

- # ====== Component Setting: PLUGIN_DE.DANIELH.DROPZONE2 ======
  id: 35216575472533788
  identification: 
    name: PLUGIN_DE.DANIELH.DROPZONE2
    type: Region

  subscription: 
    master: 
      app: 200 # FIMAKI-BACK-OFFICE
      referenced-id: 39086473410757313 # PLUGIN_DE.DANIELH.DROPZONE2

    version-number: 41720891002827

